baseURL: "https://chaeeun-h.github.io/" 
title: Chaeeun Han
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2

params:
    description: "I am a Ph.D. candidate of Information Science and Technology at the Pennsylvanis State University. . My research covers various topics.
consequat."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chaeeun Han
          subtitle: "My name is Chaeeun Han, and I am a second-year Ph.D. student in the College of Information Sciences and Technology at The Pennsylvania State University. My advisor is Dr. Aron Laszka, and my research interests lie in solving decision-making problems in data science, machine learning security, and reinforcement learning. Recently, I have been working on projects related to detecting poisoned training data using active search and forecasting transportation disruptions."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Prof. Name
          buttons:
            - name: Publications
              url: papers/
            - name: Projects
              url: projects/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: Chaeeun Han_CV_Jan_2024.pdf
        - name: Email
          url: mailto:cfh5554@psu.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=SZe3Kd8AAAAJ
        - name: GitHub
          url: https://github.com/chaeeun-h
        - name: Twitter
          url: https://twitter.com/chae-kit-out

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Chaeeun Han"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
